// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/mock_logs_repo.go -package=logs_mocks
//

// Package logs_mocks is a generated GoMock package.
package logs_mocks

import (
	log_domains "Log_service/internal/core/domains"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockLogCache is a mock of LogCache interface.
type MockLogCache struct {
	ctrl     *gomock.Controller
	recorder *MockLogCacheMockRecorder
	isgomock struct{}
}

// MockLogCacheMockRecorder is the mock recorder for MockLogCache.
type MockLogCacheMockRecorder struct {
	mock *MockLogCache
}

// NewMockLogCache creates a new mock instance.
func NewMockLogCache(ctrl *gomock.Controller) *MockLogCache {
	mock := &MockLogCache{ctrl: ctrl}
	mock.recorder = &MockLogCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogCache) EXPECT() *MockLogCacheMockRecorder {
	return m.recorder
}

// CheckUnique mocks base method.
func (m *MockLogCache) CheckUnique(ctx context.Context, arg1 uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckUnique", ctx, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckUnique indicates an expected call of CheckUnique.
func (mr *MockLogCacheMockRecorder) CheckUnique(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckUnique", reflect.TypeOf((*MockLogCache)(nil).CheckUnique), ctx, arg1)
}

// MockLogger is a mock of Logger interface.
type MockLogger struct {
	ctrl     *gomock.Controller
	recorder *MockLoggerMockRecorder
	isgomock struct{}
}

// MockLoggerMockRecorder is the mock recorder for MockLogger.
type MockLoggerMockRecorder struct {
	mock *MockLogger
}

// NewMockLogger creates a new mock instance.
func NewMockLogger(ctrl *gomock.Controller) *MockLogger {
	mock := &MockLogger{ctrl: ctrl}
	mock.recorder = &MockLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogger) EXPECT() *MockLoggerMockRecorder {
	return m.recorder
}

// LogMesage mocks base method.
func (m *MockLogger) LogMesage(event log_domains.LogEvent) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogMesage", event)
}

// LogMesage indicates an expected call of LogMesage.
func (mr *MockLoggerMockRecorder) LogMesage(event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogMesage", reflect.TypeOf((*MockLogger)(nil).LogMesage), event)
}
