CREATE SCHEMA school;

CREATE TABLE school.schools (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 1 CHECK(version>0),
    name VARCHAR(50) NOT NULL CHECK(char_length(name) BETWEEN 3 AND 50),
    description VARCHAR(1000) CHECK(char_length(description) BETWEEN 10 AND 1000)
);

CREATE TABLE school.profiles (
    id UUID PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 1 CHECK(version>0),
    login VARCHAR(100) NOT NULL CHECK(char_length(login) BETWEEN 8 AND 100),
    password VARCHAR(50) NOT NULL CHECK(char_length(password) BETWEEN 8 AND 50),
    age INTEGER NOT NULL CHECK(age>=0),
    role VARCHAR(50) NOT NULL CHECK(role IN ('ROOT', 'DIRECTOR', 'ADMIN', 'TEACHER', 'PARENT', 'STUDENT')),
    school_id INTEGER NOT NULL REFERENCES school.schools(id) ON DELETE CASCADE
);

CREATE TABLE school.rooms (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL CHECK(char_length(name) BETWEEN 1 AND 100),
    description VARCHAR(1000) CHECK(char_length(description) BETWEEN 10 AND 1000),
    floor INTEGER NOT NULL CHECK(floor>0),
    school_id INTEGER NOT NULL REFERENCES school.schools(id) ON DELETE CASCADE
);

CREATE TABLE school.places (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL CHECK(char_length(name) BETWEEN 1 AND 100),
    qr_token TEXT UNIQUE NOT NULL,
    room_id INTEGER NOT NULL REFERENCES school.rooms(id) ON DELETE CASCADE
);

CREATE TABLE school.directors (
    id UUID PRIMARY KEY REFERENCES school.profiles(id) ON DELETE CASCADE,
    first_name VARCHAR(50) NOT NULL CHECK(char_length(first_name) BETWEEN 1 AND 50
    AND
    first_name ~ '^[А-Я]'),
    surname VARCHAR(50) NOT NULL CHECK(char_length(surname) BETWEEN 1 AND 50
    AND
    surname ~ '^[А-Я]'),
    middle_name VARCHAR(50) NOT NULL CHECK(char_length(middle_name) BETWEEN 1 AND 50
    AND
    middle_name ~ '^[А-Я]'),
    room_id INTEGER NOT NULL REFERENCES school.rooms(id) ON DELETE CASCADE
);

CREATE TABLE school.admins (
    id UUID PRIMARY KEY REFERENCES school.profiles(id) ON DELETE CASCADE,
    first_name VARCHAR(50) NOT NULL CHECK(char_length(first_name) BETWEEN 1 AND 50
    AND
    first_name ~ '^[А-Я]'),
    surname VARCHAR(50) NOT NULL CHECK(char_length(surname) BETWEEN 1 AND 50
    AND
    surname ~ '^[А-Я]'),
    middle_name VARCHAR(50) NOT NULL CHECK(char_length(middle_name) BETWEEN 1 AND 50
    AND
    middle_name ~ '^[А-Я]'),
    responsibility_zone VARCHAR(100) NOT NULL CHECK(char_length(responsibility_zone) BETWEEN 1 AND 100),
    room_id INTEGER NOT NULL REFERENCES school.rooms(id) ON DELETE CASCADE
);

CREATE TABLE school.teachers (
    id UUID PRIMARY KEY REFERENCES school.profiles(id) ON DELETE CASCADE,
    first_name VARCHAR(50) NOT NULL CHECK(char_length(first_name) BETWEEN 1 AND 50
    AND
    first_name ~ '^[А-Я]'),
    surname VARCHAR(50) NOT NULL CHECK(char_length(surname) BETWEEN 1 AND 50
    AND
    surname ~ '^[А-Я]'),
    middle_name VARCHAR(50) NOT NULL CHECK(char_length(middle_name) BETWEEN 1 AND 50
    AND
    middle_name ~ '^[А-Я]'),
    subject VARCHAR(30) NOT NULL CHECK(char_length(subject) BETWEEN 1 AND 30),
    room_id INTEGER NOT NULL REFERENCES school.rooms(id) ON DELETE CASCADE
);

CREATE TABLE school.classes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(5) UNIQUE NOT NULL CHECK(char_length(name) BETWEEN 1 AND 5),
    profile VARCHAR(50) NOT NULL CHECK(char_length(profile) BETWEEN 1 AND 50),
    teacher_id UUID NOT NULL REFERENCES school.teachers(id) ON DELETE CASCADE
);

CREATE TABLE school.parents (
    id UUID PRIMARY KEY REFERENCES school.profiles(id) ON DELETE CASCADE,
    first_name VARCHAR(50) NOT NULL CHECK(char_length(first_name) BETWEEN 1 AND 50
    AND
    first_name ~ '^[А-Я]'),
    surname VARCHAR(50) NOT NULL CHECK(char_length(surname) BETWEEN 1 AND 50
    AND
    surname ~ '^[А-Я]'),
    middle_name VARCHAR(50) NOT NULL CHECK(char_length(middle_name) BETWEEN 1 AND 50
    AND
    middle_name ~ '^[А-Я]'),
    class_id INTEGER NOT NULL REFERENCES school.classes(id) ON DELETE CASCADE
);

CREATE TABLE school.students (
    id UUID PRIMARY KEY REFERENCES school.profiles(id) ON DELETE CASCADE,
    first_name VARCHAR(50) NOT NULL CHECK(char_length(first_name) BETWEEN 1 AND 50
    AND
    first_name ~ '^[А-Я]'),
    surname VARCHAR(50) NOT NULL CHECK(char_length(surname) BETWEEN 1 AND 50
    AND
    surname ~ '^[А-Я]'),
    middle_name VARCHAR(50) NOT NULL CHECK(char_length(middle_name) BETWEEN 1 AND 50
    AND
    middle_name ~ '^[А-Я]'),
    class_id INTEGER NOT NULL REFERENCES school.classes(id) ON DELETE CASCADE,
    parent_id UUID NOT NULL REFERENCES school.parents
);

CREATE TABLE school.roots (
    id UUID PRIMARY KEY REFERENCES school.profiles(id) ON DELETE CASCADE
);